[build]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/events"
  to = "/.netlify/functions/events"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
